services:
  - type: web
    name: laravel-tracking-backend
    env: docker
    plan: free
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: apache2-foreground
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:IS81zdN42TvDtJOxz7IaXMknIeGcFNKkdt0bQYD+UeU=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-tracking-backend.onrender.com
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_DEPRECATIONS_CHANNEL
        value: null
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1   # update if using Render's MySQL add-on
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: tracking_db
      - key: DB_USERNAME
        value: root         # change if using managed MySQL
      - key: DB_PASSWORD
        value: ""           # change if your DB has password
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: MEMCACHED_HOST
        value: 127.0.0.1
      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PASSWORD
        value: null
      - key: REDIS_PORT
        value: 6379
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailpit
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: null
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: Laravel
      - key: AWS_ACCESS_KEY_ID
        value: ""
      - key: AWS_SECRET_ACCESS_KEY
        value: ""
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: AWS_BUCKET
        value: ""
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: false
      - key: PUSHER_APP_ID
        value: ""
      - key: PUSHER_APP_KEY
        value: ""
      - key: PUSHER_APP_SECRET
        value: ""
      - key: PUSHER_HOST
        value: ""
      - key: PUSHER_PORT
        value: "443"
      - key: PUSHER_SCHEME
        value: https
      - key: PUSHER_APP_CLUSTER
        value: mt1
      - key: VITE_APP_NAME
        value: Laravel
      - key: VITE_PUSHER_APP_KEY
        value: ""
      - key: VITE_PUSHER_HOST
        value: ""
      - key: VITE_PUSHER_PORT
        value: "443"
      - key: VITE_PUSHER_SCHEME
        value: https
      - key: VITE_PUSHER_APP_CLUSTER
        value: mt1
